services:
  php:
    image: php:8.2-apache
    container_name: phpApacheEcoride
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysqlEcoride
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_root_password}
      MYSQL_DATABASE: ${MYSQL_database}
      MYSQL_USER: ${MYSQL_user}
      MYSQL_PASSWORD: ${MYSQL_password}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminEcoride
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${db_host}
      PMA_USER: ${db_user}
      PMA_PASSWORD: ${db_password}
    ports:
      - 8899:80

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=${mongo_server}
      - ME_CONFIG_BASICAUTH_USERNAME=${mongo_username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${mongo_password}


volumes:
  db_data:
  mongo_data: